name: Aria Linter
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Aria lint test
        id: hello
        uses: jloganolson/arialint-barebones@master
